### PR TITLE
Fix ABNF; add ABNF check to Makefile2

### PR DESCRIPTION
**Pull request by cabo**
Oops, I did this on master -- please merge with your changes in 125...

### CODE REVIEW

**Comment by brianraymor** [comment]
I do not have xpath or bap installed on my system, so I cannot validate your Makefile2 change. I'll leave that to you.

**Comment by cabo** [comment]
`gmake bap` now says

```
; host UNDEFINED
; port UNDEFINED
; path-abempty UNDEFINED
; query UNDEFINED
; fragment UNDEFINED
coap-tcp-URI = "coap+tcp://" host [ ":" port ] path-abempty [ "?" query ] [ "#" fragment ]
coaps-tcp-URI = "coaps+tcp://" host [ ":" port ] path-abempty [ "?" query ] [ "#" fragment ]
coap-ws-URI = "coap+ws://" host [ ":" port ] path-abempty [ "?" query ] [ "#" fragment ]
coaps-ws-URI = "coaps+ws://" host [ ":" port ] path-abempty [ "?" query ] [ "#" fragment ]
; coap-tcp-URI defined but not used
; coaps-tcp-URI defined but not used
; coap-ws-URI defined but not used
; coaps-ws-URI defined but not used
```

I didn't go ahead and extract those parts from 3986, but at least our parts now are parsable as ABNF.
(And the list of productions imported from 3986 in {{URI}} is identical to the list of productions undefined above.)

**Comment by cabo** [comment]
Hmm, the "push" CI job fails but the "pr" CI job succeeds.  Need to understand why the former is using a directory that doesn't exist.  But that doesn't detract from this PR being ready to merge.

**Comment by cabo** [comment]
(CI failure now https://github.com/martinthomson/i-d-template/issues/93)

**Comment by cabo** [comment]
Full output from `gmake -f Makefile2 bap abnfgen`:

```
bap full.abnf
coap-tcp-URI = "coap+tcp://" host [ ":" port ] path-abempty [ "?" query ] [ "#" fragment ]
coaps-tcp-URI = "coaps+tcp://" host [ ":" port ] path-abempty [ "?" query ] [ "#" fragment ]
coap-ws-URI = "coap+ws://" host [ ":" port ] path-abempty [ "?" query ] [ "#" fragment ]
coaps-ws-URI = "coaps+ws://" host [ ":" port ] path-abempty [ "?" query ] [ "#" fragment ]
host = IP-literal / IPv4address / reg-name
IP-literal = "[" ( IPv6address / IPvFuture ) "]"
IPvFuture = "v" 1*HEXDIG "." 1*( unreserved / sub-delims / ":" )
IPv6address = ( 6( h16 ":" ) ls32 ) / ( "::" 5( h16 ":" ) ls32 ) / ( [ h16 ] "::" 4( h16 ":" ) ls32 ) / ( [ [ h16 ":" ] h16 ] "::" 3( h16 ":" ) ls32 ) / ( [ *2( h16 ":" ) h16 ] "::" 2( h16 ":" ) ls32 ) / ( [ *3( h16 ":" ) h16 ] "::" h16 ":" ls32 ) / ( [ *4( h16 ":" ) h16 ] "::" ls32 ) / ( [ *5( h16 ":" ) h16 ] "::" h16 ) / ( [ *6( h16 ":" ) h16 ] "::" )
ls32 = ( h16 ":" h16 ) / IPv4address
h16 = 1*4HEXDIG
IPv4address = dec-octet "." dec-octet "." dec-octet "." dec-octet
dec-octet = DIGIT / ( %x31-39 DIGIT ) / ( "1" 2DIGIT ) / ( "2" %x30-34 DIGIT ) / ( "25" %x30-35 )
reg-name = *( unreserved / pct-encoded / sub-delims )
pct-encoded = "%" HEXDIG HEXDIG
HEXDIG = DIGIT / "A" / "B" / "C" / "D" / "E" / "F"
DIGIT = %x30-39
ALPHA = %x41-5A / %x61-7A
unreserved = ALPHA / DIGIT / "-" / "." / "_" / "~"
sub-delims = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="
path-abempty = *( "/" segment )
segment = *pchar
pchar = unreserved / pct-encoded / sub-delims / ":" / "@"
port = *DIGIT
query = *( pchar / "/" / "?" )
fragment = *( pchar / "/" / "?" )
; coap-tcp-URI defined but not used
; coaps-tcp-URI defined but not used
; coap-ws-URI defined but not used
; coaps-ws-URI defined but not used
abnfgen -s coap-tcp-URI full.abnf; echo ""
cOaP+TcP://[aF:DB:Ca::A]:/!/)/#@
abnfgen -s coaps-tcp-URI full.abnf; echo ""
COapS+TcP://[::c:DE5]:17#.///
abnfgen -s coap-ws-URI full.abnf; echo ""
cOaP+WS://252.255.107.233
abnfgen -s coaps-ws-URI full.abnf; echo ""
COAPS+ws://5.5.89.232:5
```

**Comment by cabo** [comment]
While most of this PR are test harnesses that will prevent regression, the change to the .md (the actual ABNF fix) is critical.

**Pull request merged**
